CS_study/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^collection/', include('collection.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# author: wangfp time:2017/9/25

from django.conf.urls import url

from . import views

app_name = 'article'
urlpatterns = [
    url(r'^$', views.posts, name='posts'),
    url(r'^category/(?P<cat_slug>[\w\-]+)/$', views.cat_post, name='cat_post'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/user/personal/$', views.post_person, name='post_person'),
    url(r'^post/author/(?P<username>[\w\@\.\+\-\_]+)/$', views.post_author, name='post_author'),
    url(r'^post/user/add/$', views.post_add, name='post_add'),
    url(r'^post/user/edit/(?P<pk>[0-9]+)/$', views.post_edit, name='post_edit'),
    url(r'^post/user/delete/(?P<pk>[0-9]+)/$', views.post_delete, name='post_delete'),
    url(r'^post/user/like/$', views.post_like, name='post_like'),
    url(r'^post/user/like_cancel/$', views.post_like_cancel, name='post_like_cancel'),
]

collection/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# author: wangfp time:2017/9/25

from django.conf.urls import url

from . import views

app_name = 'collection'
urlpatterns = [
    url(r'^websites/$', views.websites, name='websites'),
    url(r'^website/add', views.add_website, name='add_website'),
    url(r'^category/(?P<cat_slug>[\w\-]+)/$', views.cat_web, name='cat_web'),
    url(r'^website/collected/$', views.web_collected, name='web_collected'),
    url(r'^website/collected/cancel/$', views.collected_cancel, name='collected_cancel'),
]

main/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# author: wangfp time:2017/9/25

from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.to_index),
    url(r'^index/$', views.index, name='index'),
    url(r'^add_category/$', views.add_category, name='add_category'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="zh">
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">
    <!--<link href="http://www.bootcss.com/p/layoutit/css/layoutit.css" rel="stylesheet">-->
    <!--<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">-->
    <link href="{% static '/css/layoutit.css' %}" rel="stylesheet">
	<link href="{% static '/css/my.css' %}" rel="stylesheet">
	<link href="{% static '/css/highlights/borland.css' %}" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<ul class="nav nav-tabs font-size-1">
				<li>
					<a href="{% url 'index' %}">首页</a>
				</li>
				<li>
					<a href="{% url 'article:posts' %}">记录</a>
				</li>
				<li>
					<a href="{% url 'collection:websites' %}">点滴</a>
				</li>
				{% if user.is_authenticated %}
				<li class="pull-right">
					<a href="{% url 'logout' %}?next={% url 'article:posts' %}">退出登录</a>
				</li>
				<li class="pull-right dropdown">
					<a href="#" data-toggle="dropdown" class="dropdown-toggle">您好，{{ user.username }}<strong class="caret"></strong></a>
					<ul class="dropdown-menu">
						<li>
							<a href="{% url 'article:post_person' %}">个人文章</a>
						</li>
						<li>
							<a href="{% url 'article:post_add' %}">文章写作</a>
						</li>
						<li>
							<a href="{% url 'collection:add_website' %}">添加网站</a>
						</li>
						<li>
							<a href="{% url 'add_category' %}">添加分类</a>
						</li>
						<li class="divider"></li>
						<li>
							<a href="{% url 'profile_show' %}">个人信息</a>
						</li>
						<li>
							<a href="{% url 'password_change' %}">修改密码</a>
						</li>
					</ul>
				</li>
				{% else %}
				<li class="pull-right">
					<a href="{% url 'register' %}">注册</a>
				</li>
				<li class="pull-right">
					<a href="{% url 'login' %}?next={% url 'index' %}">登录</a>
					<ul class="dropdown-menu">
						<li>
							<a href="{% url 'add_category' %}">添加分类</a>
						</li>
						<li>
							<a href="{% url 'article:post_add' %}">写作文章</a>
						</li>
						<li>
							<a href="{% url 'collection:add_website' %}">增加收集</a>
						</li>
						<li class="divider">
						</li>
						<li>
							<a href="#">分割线</a>
						</li>
					</ul>
				</li>
				{% endif %}
			</ul>
		</div>
	</div>
	<div class="row">
		<div class="col-md-9">
			{% block body %}
            {% endblock %}
		</div>
		<div class="col-md-3 sidebar">
			{% block sidebar %}
			{% endblock %}
		</div>
	</div>
</div>

<script src="http://libs.baidu.com/jquery/1.9.1/jquery.min.js"></script>
<script src="http://www.bootcss.com/p/layoutit/js/bootstrap.min.js"></script>
<script src="{% static 'js/my_jquery.js' %}"></script>
<script src="{% static 'js/my_ajax.js' %}"></script>
<!--<script src="http://www.bootcss.com/p/layoutit/js/jquery-ui.js"></script>-->
<!--<script src="http://www.bootcss.com/p/layoutit/js/jquery.ui.touch-punch.min.js"></script>-->
<!--<script src="http://www.bootcss.com/p/layoutit/js/jquery.htmlClean.js"></script>-->
<!--<script src="http://www.bootcss.com/p/layoutit/ckeditor/ckeditor.js"></script>-->
<!--<script src="http://www.bootcss.com/p/layoutit/ckeditor/config.js"></script>-->
<!--<script src="http://www.bootcss.com/p/layoutit/js/scripts.js"></script>-->
<!--<script src="{% static '/js/jquery.min.js' %}"></script>-->
<!--<script src="{% static '/js/bootstrap.min.js' %}"></script>-->

</body>
</html>

templates/cats.html
<div class="page-header"><h4>分类</h4></div>
{% if cat_list %}
<ul>
    {% for cat in cat_list %}
        <li><a href="{% url  url_name  cat.slug %}">{{ cat.name }}</a></li>

    {% endfor %}
</ul>
{% else %}
<p>尚没有分类</p>
{% endif %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
	首页
{% endblock %}

{% block body %}
<div class="jumbotron">
    <h1>学以致用</h1>
</div>
<div class="page-header">
    <h2>知识总结与心得</h2>
</div>
{% if post_list %}
<div class="row">
    {% for post in post_list %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <h4 class="text-center">
                {{ post.title }}
            </h4>
            <p class="text-center">
                <a href="{% url 'article:post_author' post.auth.username %}">作者：{{ post.auth }}</a>
            </p>
            <p>
                {{ post.excerpt }}
            </p>
            <p>
                <a href="{% url 'article:post_detail' post.pk %}">查看更多 »</a>
            </p>
            <a href="{% url 'article:cat_post' post.category.slug %}">
                <span class="label label-primary">{{ post.category.name }}</span>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>尚未编辑文章</p>
{% endif %}

<hr />
<p class="text-right"><a href="{% url 'article:posts' %}">查看更多 »</a></p>

<div class="page-header">
    <h2>CS知识学习网站收集</h2>
</div>
{% if web_list %}
<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        标题
                    </th>
                    <th>
                        类型
                    </th>
                    <th>
                        介绍
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for web in web_list %}
                <tr>
                    <td>
                        <a href="{{ web.url }}">{{ web.title }}</a>
                    </td>
                    <td>
                        <a href="{% url 'collection:cat_web' web.category.slug %}">{{ web.category.name }}</a>
                    </td>
                    <td>
                        {{ web.describe }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<p class="text-right"><a href="{% url 'collection:websites' %}">查看更多 »</a></p>
{% else %}
<p>尚未收集到网站</p>
{% endif %}

{% endblock %}

{% block sidebar %}
    <div class="page-header"><h4>分类</h4></div>
    {% if cat_list %}
    <ul>
        {% for cat in cat_list %}
        <li>
            {{ cat.name }}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>尚未添加分类</p>
    {% endif %}

    <div class="page-header"><h4>标签</h4></div>
    {% if tag_list %}
        {% for tag in tag_list %}
        <span class="label label-info">{{ tag.name }}</span>
        {% endfor %}
    {% else %}
    <p>尚未添加标签</p>
    {% endif %}
{% endblock %}