CS_study/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^collection/', include('collection.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# author: wangfp time:2017/9/25

from django.conf.urls import url

from . import views

app_name = 'article'
urlpatterns = [
    url(r'^$', views.posts, name='posts'),
    url(r'^category/(?P<cat_slug>[\w\-]+)/$', views.cat_post, name='cat_post'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/user/personal/$', views.post_person, name='post_person'),
    url(r'^post/author/(?P<username>[\w\@\.\+\-\_]+)/$', views.post_author, name='post_author'),
    url(r'^post/user/add/$', views.post_add, name='post_add'),
    url(r'^post/user/edit/(?P<pk>[0-9]+)/$', views.post_edit, name='post_edit'),
    url(r'^post/user/delete/(?P<pk>[0-9]+)/$', views.post_delete, name='post_delete'),
    url(r'^post/user/like/$', views.post_like, name='post_like'),
    url(r'^post/user/like_cancel/$', views.post_like_cancel, name='post_like_cancel'),
]

main/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# author: wangfp time:2017/9/25

from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.to_index),
    url(r'^index/$', views.index, name='index'),
    url(r'^add_category/$', views.add_category, name='add_category'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.utils.html import strip_tags
import markdown

from main.models import Category, Tag


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    mark_down = models.BooleanField(default=False)
    auth = models.ForeignKey(User)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:100]
        super().save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('article:post_detail', args=(self.pk,))

article/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
# author: wangfp time:2017/9/26

from django import forms

from .models import Post, Tag
from main.models import Category


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='标题')
    excerpt = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='摘要',
                              required=False, help_text='（可选内容）')
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '40'}), label='文章')
    category = forms.ModelChoiceField(Category.objects.all(),
                                      widget=forms.Select(attrs={'class': 'form-control'}),
                                      label='类型')
    mark_down = forms.BooleanField(label='使用markdown', required=False)

    class Meta:
        model = Post
        fields = ('title', 'excerpt', 'mark_down', 'body', 'category')

article/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth.models import User

import markdown

from .models import Post
from .forms import PostForm
from main.models import Category
from account.models import UserProfile


def posts(request):
    post_list = Post.objects.all()
    cat_list = Category.objects.all()
    return render(request, 'article/posts.html', {'post_list': post_list,
                                                  'cat_list': cat_list})


def cat_post(request, cat_slug):
    cat = get_object_or_404(Category, slug=cat_slug)
    post_list = Post.objects.filter(category=cat)
    cat_name = cat.name
    cat_list = Category.objects.all()
    return render(request, 'article/posts.html', {'post_list': post_list,
                                                  'cat_list': cat_list,
                                                  'cat_name': cat_name})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.views += 1
    post.save()
    if post.mark_down:
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])

    user = request.user
    liked = False
    profiled = False
    if user.is_authenticated():
        try:
            profile = UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            return render(request, 'article/post_detail.html', {'post': post, 'profiled': profiled})
        profiled = True
        if post in profile.likes.all():
            liked = True
    return render(request, 'article/post_detail.html', {'post': post, 'liked': liked, 'profiled': profiled})


def post_author(request, username):
    if username == request.user.username:
        return redirect(reverse('article:post_person'))
    post_list = get_list_or_404(Post, auth__username=username)
    return render(request, 'article/posts.html', {'post_list': post_list,
                                                  'username': username})


@login_required
def post_person(request):
    user = request.user
    person = True
    post_list = Post.objects.filter(auth=user)
    return render(request, 'article/posts.html', {'post_list': post_list,
                                                  'person': person})


@login_required
def post_add(request):
    form = PostForm()
    user = request.user
    try:
        UserProfile.objects.get(user=user)
    except UserProfile.DoesNotExist:
        return render(request, 'account/profile_need.html')

    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.auth = user
            post.save()
            return redirect(reverse('article:post_detail', args=(post.pk,)))
        else:
            print(form.errors)

    return render(request, 'article/post_add.html', {'form': form})


@login_required
def post_edit(request, pk):
    user = request.user
    post = get_object_or_404(Post, pk=pk)
    if post.auth != user:
        return redirect(reverse('index'))

    form = PostForm()
    form['title'].initial = post.title
    form['excerpt'].initial = post.excerpt
    form['body'].initial = post.body
    form['category'].initial = post.category
    form['mark_down'].initial = post.mark_down
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            # 注意：此处不可直接使用form.save()，这样会新创建一个文章
            post.title = form.cleaned_data['title']
            post.excerpt = form.cleaned_data['excerpt']
            post.body = form.cleaned_data['body']
            post.category = form.cleaned_data['category']
            post.mark_down = form.cleaned_data['mark_down']
            post.save()
            return redirect(post)
        else:
            print(form.errrors)

    return render(request, 'article/post_edit.html', {'form': form,
                                                      'post': post})


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = request.user
    if user != post.auth:
        redirect('index')

    title = post.title
    post.delete()
    return render(request, 'article/post_delete.html', {'delete_title': title})


@login_required
def post_like(request):
    post_id = None
    if request.method == 'GET':
        post_id = request.GET['post_id']
    likes = 0
    if post_id:
        post = Post.objects.get(id=(int(post_id)))
        if post:
            user = request.user
            profile = UserProfile.objects.get(user=user)
            profile.likes.add(post)
            likes = post.userprofile_set.count()
            post.likes = likes
            post.save()
    return HttpResponse(likes)


@login_required
def post_like_cancel(request):
    post_id = None
    if request.method == 'GET':
        post_id = request.GET['post_id']
    likes = 0
    if post_id:
        post = Post.objects.get(id=(int(post_id)))
        if post:
            user = request.user
            profile = UserProfile.objects.get(user=user)
            profile.likes.remove(post)
            likes = post.userprofile_set.count()
            post.likes = likes
            post.save()
    return HttpResponse(likes)

templates/article/base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load main_template_tags %}

{% block sidebar %}
    {% get_category_list 'article' %}
{% endblock %}

templates/article/post_add.html
{% extends 'article/base.html' %}
{% load staticfiles %}

{% block title %}
    写文章
{% endblock %}

{% block body %}
<h1>请在此处编辑您的文章：</h1>
<hr />

<div class="row">
    <div class="col-md-12">
        <form role="form" action="{% url 'article:post_add' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.title.errors }}
                {{ form.title.label_tag }}
                {{ form.title }}
                <span class="text-info">{{ form.title.help_text|safe }}</span>
            </div>
            <div class="form-group">
                {{ form.excerpt.errors }}
                {{ form.excerpt.label_tag }}
                {{ form.excerpt }}
                <span class="text-info">{{ form.excerpt.help_text|safe }}</span>
            </div>
            <div class="form-group row">
                {{ form.mark_down.errors }}
                <label for="{{ form.category.id_for_label }}" class="col-md-2">{{ form.mark_down.label }}</label>
                <div class="col-md-1">{{ form.mark_down }}</div>
                <span class="text-info">{{ mark_down.excerpt.help_text|safe }}</span>
            </div>
            <div class="form-group">
                {{ form.body.errors }}
                {{ form.body.label_tag }}
                {{ form.body }}
                <span class="text-info">{{ form.body.help_text|safe }}</span>
            </div>
            <div class="form-group row">
                {{ form.category.errors }}
                <label for="{{ form.category.id_for_label }}" class="col-md-1">{{ form.category.label }}</label>
                <div class="col-md-4">{{ form.category }}</div>
                <span class="text-info">{{ form.category.help_text|safe }}</span>
            </div>
            <button class="btn btn-primary" type="submit" name="submit">提交文章</button>
        </form>
    </div>
</div>
{% endblock %}

templates/article/post_delete.html
{% extends 'article/base.html' %}
{% load staticfiles %}

{% block title %}
成功删除文章
{% endblock %}

{% block body %}
<h3 class="text-success">文章<strong>'{{ delete_title }}'</strong>已经成功删除</h3>
{% endblock %}

templates/article/post_detail.html
{% extends 'article/base.html' %}
{% load staticfiles %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block body %}
{% if success %}
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  文章修改成功！
</div>
{% endif %}
<div class="col-md-12">
    <div class="page-header">
        <h1 class="text-center text-header">
            {{ post.title }}
        </h1>
    </div>
        <div class="entry-meta">
            <span class="post-author">
                <a href="{% url 'article:post_person' %}">{{ post.auth.username }}</a>
            </span>
            <span class="post-category">
                {{ post.category.name }}
            </span>
            <span class="post-date">
                {{ post.created_time }} 创作
            </span>
            <span class="views-count">
                {{ post.views }} 阅读
            </span>
            <span class="likes-count">
                {{ post.likes }} 喜欢
            </span>
        </div>
    <div class="col-md-10 col-md-offset-1">
        <p class="text-left">
            {{ post.body|safe }}
        </p>
        <hr />
    </div>

    {% if post.auth == user %}
    <div class="col-md-2 col-md-offset-1">
        <a href="{% url 'article:post_edit' post.id %}" class="btn btn-primary btn-block" role="button">修改文章</a>
    </div>
    <div class="col-md-2 col-md-offset-6">
        <a href="{% url 'article:post_delete' post.id %}" class="btn btn-warning btn-block" role="button">删除文章</a>
    </div>
    {% elif liked %}
    <div class="col-md-2 col-md-offset-1">
        <button class="btn btn-default btn-block" id="like-cancel" data-postid="{{ post.id }}" type="button">
            取消喜欢 <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        </button>
    </div>
    {% elif user.is_authenticated and profiled %}
    <div class="col-md-2 col-md-offset-1">
        <button class="btn btn-default btn-block" id="likes" data-postid="{{ post.id }}" type="button">
            喜欢 <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        </button>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/article/post_edit.html
{% extends 'article/base.html' %}
{% load staticfiles %}

{% block title %}
    写文章
{% endblock %}

{% block body %}
<h1>请在此处修改您的文章：</h1>
<hr />

<div class="row">
    <div class="col-md-12">
        <form role="form" action="{% url 'article:post_edit' post.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.title.errors }}
                {{ form.title.label_tag }}
                {{ form.title }}
                <span class="text-info">{{ form.title.help_text|safe }}</span>
            </div>
            <div class="form-group">
                {{ form.excerpt.errors }}
                {{ form.excerpt.label_tag }}
                {{ form.excerpt }}
                <span class="text-info">{{ form.excerpt.help_text|safe }}</span>
            </div>
            <div class="form-group row">
                {{ form.mark_down.errors }}
                <label for="{{ form.category.id_for_label }}" class="col-md-2">{{ form.mark_down.label }}</label>
                <div class="col-md-1">{{ form.mark_down }}</div>
                <span class="text-info">{{ mark_down.excerpt.help_text|safe }}</span>
            </div>
            <div class="form-group">
                {{ form.body.errors }}
                {{ form.body.label_tag }}
                {{ form.body }}
                <span class="text-info">{{ form.body.help_text|safe }}</span>
            </div>
            <div class="form-group row">
                {{ form.category.errors }}
                <label for="{{ form.category.id_for_label }}" class="col-md-1">{{ form.category.label }}</label>
                <div class="col-md-4">{{ form.category }}</div>
                <span class="text-info">{{ form.category.help_text|safe }}</span>
            </div>
            <button class="btn btn-primary" type="submit" name="submit">提交修改</button>
        </form>
    </div>
</div>
{% endblock %}

templates/article/posts.html
{% extends 'article/base.html' %}
{% load staticfiles %}

{% block title %}
知识总结与心得
{% endblock %}

{% block body %}
    <div class="jumbotron">
        <h1>
            {% if person %}
            {{ user }}的文章
            {% elif username %}
            {{ username }}的文章
            {% else %}
            知识总结与心得
            {% endif %}
        </h1>
        {% if cat_name %}
            <h2><span class="label label-default">{{ cat_name }}</span></h2>
        {% elif person %}
            <a href="{% url 'article:post_add' %}" class="btn btn-default" role="button">文章写作</a>
        {% endif %}
    </div>

    {% if post_list %}
    {% for post in post_list %}
    <div class="col-md-12">
        <h3 class="text-center text-header">
            {{ post.title }}
        </h3>
        <div class="entry-meta">
            <span class="post-author">
                <a href="{% url 'article:post_author' post.auth.username %}">{{ post.auth.username }}</a>
            </span>
            <span class="post-category">
                <a href="{% url 'article:cat_post' post.category.slug %}">{{ post.category.name }}</a>
            </span>
            <span class="post-date">
                {{ post.created_time }} 创作
            </span>
            <span class="views-count">
                {{ post.views }} 阅读
            </span>
            <span class="likes-count">
                {{ post.likes }} 喜欢
            </span>
        </div>
        <div class="col-md-10 col-md-offset-1">
            <p class="font-size-1">
                {{ post.excerpt }}
            </p>
            <p>
                <a href="{% url 'article:post_detail' post.pk %}">查看更多 »</a>
            </p>
        </div>

    </div>
    {% endfor %}
    {% else %}
    <p>暂无发表的文章</p>
    {% endif %}
{% endblock %}